using Common.DotNetCode;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace Busines.IDAO
{
    public interface IMPC_Person_IDAO
    {
        DataTable PersonLogin(string name, string password, string loginName);
        int validname(string loginName);
        int validmail(string email);
        int validmobile(string mobile);
        int validemailcode(string email, string emailcode);
        DataTable getpolity(string value);
        DataTable getNation(string value);
        DataTable getmarriage(string value);
        DataTable getgradtype(string value);
        DataTable geteduType(string value);
        DataTable geteduBack(string value);
        DataTable getedubatch(string value);
        DataTable getgradeType(string value);
        int overstep(string userID);
        int overstep();
        Hashtable allstep(string userID);
        Hashtable allstep();
        DataTable getCity(string cityID);
        DataTable GetCompanyListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        bool IsFreshs(string specID, string UserID);
        bool IsFreshs(string specID);
        bool IsFresh(string UserID);
        bool IsFresh();
        int ApplySpec(string specID);
        DataTable GetApply(string UserID);
        DataTable GetApply();
        DataTable getPaperLevel(string value);
        DataTable getResearchLevel(string value);
        DataTable getAttachmentType(string value);
        DataTable getFamilyCall(string value);
        DataTable getLanguageName(string value);
        DataTable getLanguageLevel(string value);
        DataTable getWorkType(string value);
        DataTable getDegree(string value);
        DataTable getSchool_Area(string value);
        DataTable getSchool_Info(string searchstr, string SchoolArea);
        DataTable getEducation(string EduID, string UserID);
        DataTable getEducation(string EduID);
        DataTable getEducation();
        DataTable getFirstEducation(string UserID, string EduID);
        DataTable getFirstEducation(string EduID);
        DataTable getFirstEducation();
        DataTable GetFamily(string UserID);
        DataTable GetFamily();
        void ChangeStep(string UserID, string steps, int state);
        void ChangeStepT(string steps);
        void ChangeStepF(string steps);
        DataTable GetWork(string UserID);
        DataTable GetWork();
        int WorkDel(string ID);
        DataTable getAwardLevel(string value);
        DataTable GetAward(string UserID);
        DataTable GetAward();
        int AwardDel(string ID);
        DataTable GetPaper(string UserID);
        DataTable GetPaper();
        DataTable GetResearch(string UserID);
        DataTable GetResearch();
        DataTable GetAttachment(string UserID);
        DataTable GetAttachment();
        string GetUploadPath();
        string GetUserUploadPath();
        string GetWebPath();
        string GetUserWebPath();
        bool IsUserCheck();
        DataTable GetNewsListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        int PaperDel(string ID);
        int ResearchDel(string ID);
        int AttachmentDel(string ID);
        int FamilyDel(string ID);
        int EducationDel(string ID);
        DataTable GetUserInfo(string UserID);
        DataTable GetUserInfo();
        DataTable GetLanguage(string UserID);
        DataTable GetLanguage();
        DataTable GetComputerLevel(string UserID);
        DataTable GetComputerLevel();
        DataTable GetCertOther(string UserID);
        DataTable GetCertOther();
        DataTable GetCompany();
        DataTable GetSpecialty(string CompyID, string stand);
        DataTable GetSpecialty(string CompyID);
        DataTable GetUserSpecialty(string CompyID);
        bool IsSpecialtyNormal(string specID);
        int LanguageDel(string ID);
        int ComputerDel(string ID);
        int CertOtherDel(string ID);
        DataTable GetUserListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        DataTable GetUserID(StringBuilder SqlWhere, IList<SqlParam> IList_param);
        DataTable GetSpecialtyListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        int ChangeStatus(string User_ID, string status);
        int ChangeLock(string User_ID, string locks);
        int AddFlag(string sysUserID, string User_ID);
        void UpdateMessage(string MsgID);
        int ReCheckUser(string UserID);
        DataTable GetFlagListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        int DeleteFlag(string sysUserID, string User_ID);
        DataTable GetMessageListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        DataTable GetUserMessageTempListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        int UpdateSendMessage(string MsgID);
        int CreateSendMessage(string sysUserID, string MessageType, string MsgTitle, string MsgInfo, string User_ID);
        DataTable GetFeedbackListPage(StringBuilder SqlWhere, IList<SqlParam> IList_param, int pageIndex, int pageSize, ref int count);
        int ReadFeedback(string FeedID);
        bool ExistAttaIDCard(string User_ID);
       // string ExportExcelFile(string sqlstr, string tablename);
        string ExportExcelFilebyUserID(string User_ID);
        int InPortExcel(StringBuilder sqlstr);

        string ExportExcelFilebySQL(StringBuilder strsql);

    }
}
